name: jaspr_ui_library
description: A new jaspr project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  jaspr: ^0.16.1
  jaspr_router: ^0.6.0
  jaspr_ui:
    git:
     url:  https://github.com/anoochit/jaspr_ui.git
     ref: daisyui

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_builder: ^0.16.1
  jaspr_lints: ^0.1.2
  jaspr_tailwind: ^0.3.0
  jaspr_web_compilers: ^4.0.10+1
  lints: ^3.0.0

jaspr:
  mode: static
